name: docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        include:
          - python: 3.8
            alpine: 3.13
            pdm: 1.10.1
          - python: 3.9
            alpine: 3.14
            pdm: 1.10.1
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push python ${{ matrix.python }} / alpine ${{ matrix.alpine }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: carstencodes/pdm-alpine:${{ matrix.pdm }}-python${{ matrix.python }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            ALPINE_VERSION=${{ matrix.alpine }}
            PDM_VERSION=${{ matrix.pdm }}
