name: docker

on:
  push:
    branches:
      - 'main'
      - 'ci/test'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    env:
      USED_PDM_VERSION: 1.12.1
      USED_GITLAB_CLI_VERSION: 2.10.1
    strategy:
      matrix:
        include:
          - python: 3.8
            alpine: 3.13
          - python: 3.9
            alpine: 3.14
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check if on main branch
        shell: bash
        run: | 
          [ "${GITHUB_REF#refs/heads/}" == "main" ] && echo "##[set-output name=is_main_branch;]$(echo true)" 
          [ "${GITHUB_REF#refs/heads/}" != "main" ] && echo "##[set-output name=is_main_branch;]$(echo false)"
        id: runs_on_main
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build all images with python ${{ matrix.python }} / alpine ${{ matrix.alpine }} without pushing
        uses: docker/build-push-action@v2
        if: ${{steps.runs_on_main.outputs.is_main_branch == 'false'}}
        with:
          context: .
          push: false
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            ALPINE_VERSION=${{ matrix.alpine }}
            PDM_VERSION=${{env.USED_PDM_VERSION}}
            GITLAB_CLI_VERSION=${{env.USED_GITLAB_CLI_VERSION}}
      -
        name: Build and push base image with python ${{ matrix.python }} / alpine ${{ matrix.alpine }}
        uses: docker/build-push-action@v2
        if: ${{steps.runs_on_main.outputs.is_main_branch}}
        with:
          context: .
          target: base
          push: true
          tags: carstencodes/pdm-alpine:${{env.USED_PDM_VERSION}}-python${{ matrix.python }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            ALPINE_VERSION=${{ matrix.alpine }}
            PDM_VERSION=${{env.USED_PDM_VERSION}}
      -
        name: Build and push gitlab image with python ${{ matrix.python }} / alpine ${{ matrix.alpine }} / gitlab ${{env.USED_GITLAB_CLI_VERSION}}
        uses: docker/build-push-action@v2
        if: ${{steps.runs_on_main.outputs.is_main_branch}}   
        with:
          context: .
          target: gitlab
          push: true
          tags: carstencodes/pdm-alpine:${{env.USED_PDM_VERSION}}-python${{ matrix.python }}-gitlab${{env.USED_GITLAB_CLI_VERSION}}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            ALPINE_VERSION=${{ matrix.alpine }}
            PDM_VERSION=${{env.USED_PDM_VERSION}}
            GITLAB_CLI_VERSION=${{env.USED_GITLAB_CLI_VERSION}}
